### ISSUE TITLE
hello, hi I have an error when starting comfyui

### ISSUE THREAD

**Issue by nikolaiusa** [ttulttul/ComfyUI-Iterative-Mixer#11]
```
Traceback (most recent call last):
  File "I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Iterative-Mixer\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Iterative-Mixer\nodes.py", line 18, in <module>
    from .samplers import SAMPLERS_MAP, BLENDING_FUNCTION_MAP, BLENDING_SCHEDULE_MAP
  File "I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Iterative-Mixer\samplers\__init__.py", line 11, in <module>
    from ..utils import generate_class_map, generate_noised_latents, slerp, _trace
  File "I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Iterative-Mixer\utils\__init__.py", line 32, in <module>
    def generate_noised_latents(x, sigmas, normalize=False):
TypeError: no_grad.__init__() takes 1 positional argument but 2 were given

Cannot import I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Iterative-Mixer module for custom nodes: no_grad.__init__() takes 1 positional argument but 2 were given
```

**Comment by adolfocesar1** [comment]
same here

**Comment by elphamale** [comment]
I have the same error as the guys above. 
I did comfyui-manager 'try fix' then delete and reinstall. 
Then I did fresh clone as per suggestion above.
None of these steps helped.

**Comment by ttulttul** [comment]
This issue has been fixed with the latest commit. Sorry for the hassle!

**Comment by nikolaiusa** [comment]
thx
