### ISSUE TITLE
Error when running workflow "Differential Diffusion.png"

### ISSUE THREAD

**Issue by lldacing** [ttulttul/ComfyUI-Iterative-Mixer#25]
Traceback (most recent call last):
  File "F:\sdwork\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\sdwork\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\sdwork\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\sdwork\ComfyUI\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 326, in sample
    samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, latent_image, noise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise_seed)
  File "F:\sdwork\ComfyUI\ComfyUI\comfy\sample.py", line 113, in sample_custom
    samples = comfy.samplers.sample(real_model, noise, positive_copy, negative_copy, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\sdwork\ComfyUI\ComfyUI\comfy\samplers.py", line 627, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "F:\sdwork\ComfyUI\ComfyUI\comfy\samplers.py", line 566, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\installed\Python\anaconda3\envs\comfyUI\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\sdwork\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Iterative-Mixer\samplers\__init__.py", line 261, in __call__
    x = self.run(model, x, sigmas, c1=c1,
  File "D:\installed\Python\anaconda3\envs\comfyUI\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\sdwork\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Iterative-Mixer\samplers\__init__.py", line 175, in run
    denoise_mask, _ = our_model.get_masks(sigma, denoise_mask)
  File "D:\installed\Python\anaconda3\envs\comfyUI\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\sdwork\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Iterative-Mixer\samplers\__init__.py", line 52, in get_masks
    denoise_mask = self.model_options["denoise_mask_function"](sigma, denoise_mask, extra_options={"model": self.inner_model, "sigmas": self.sigmas})
  File "F:\sdwork\ComfyUI\ComfyUI\comfy_extras\nodes_differential_diffusion.py", line 30, in forward
    current_ts = model.inner_model.model_sampling.timestep(sigma[0])
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

**Comment by ttulttul** [comment]
I'll have a look. Can you please attach your workflow so that I can replicate?

**Comment by poluramus** [comment]
I have the exact same error using the "Differential Diffusion.png" workflow provided in your exemples. I tried with sdxl and sd1.5.

Thank you 👍

**Comment by ttulttul** [comment]
Thanks. Must be something that broke in a recent update. I'll sync up and test things out.

**Comment by poluramus** [comment]
> Thanks. Must be something that broke in a recent update. I'll sync up and test things out.

No problem. Ask if it's working on your end and you need want more informations.

**Comment by ttulttul** [comment]
This is fixed in the latest commit.
